name: Create Release PR
on:
  workflow_dispatch:
    inputs:
      semver-type:
        required: false
    branches:
      - 'main'
      - '[0-9]+.[1-9][0-9]*.x'

defaults:
  run:
    shell: bash
jobs:
  prepare:
    name: Prepare release run
    runs-on: ubuntu-20.04
    steps:
    - name: Check SemVer input
      env:
        SEMVER_TYPE: ${{ github.event.inputs.semver-type }}
      run: |
        if [[ ! -z "$SEMVER_TYPE" ]]; then
          echo "SemVer Type is defined. Checking for valid SemVer type..."
          if [[ "$SEMVER_TYPE" == "major" ]] || [[ "$SEMVER_TYPE" == "minor" ]] || [[ "$SEMVER_TYPE" == "patch" ]]; then
            echo "::notice::SemVer Type is correctly set to $SEMVER_TYPE! Continuing with this version bump..."
          else
            echo "::error::ERROR: Enforced SemVer does not match any of [major,minor,patch]!"
            echo "Exiting..."
            exit 1
          fi
        else
          echo "::notice::No SemVer type defined, continuing with auto generated version number..."
        fi

    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Find next version number
      id: version_number
      env:
        SEMVER_TYPE: ${{ github.event.inputs.semver-type }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npx release-please@^14.1.0 release-pr \
          --token="$GH_TOKEN" \
          --repo-url=philipp-hinteregger/release-please-test \
          --dry-run=true > release-please-output

        echo "::set-output name=RELEASE_VERSION::$(cat release-please-output | grep '): release' | cut -d ' ' -f4)"
        
    - name: Debug next version
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: | 
        echo "$(npx release-please@^14.1.0 release-pr \
          --token=$GH_TOKEN \
          --repo-url=philipp-hinteregger/release-please-test \
          --dry-run=true > release-please-output)"

    - name: Output new version
      env:
        VERSION_OUT: ${{ steps.version_number.outputs.RELEASE_VERSION }}
      run: |
        echo $VERSION_OUT

    - name: Find current branch
      id: extract_branch
      run: |
        branch=${GITHUB_REF#refs/heads/}
        echo "::set-output name=branch::${branch}"

    - name: Output target branch
      env:
        TARGET_BRANCH: ${{ steps.extract_branch.outputs.branch }}
      run: |
        echo $TARGET_BRANCH

    - name: Create release
      id: create_release
      env:
        SEMVER_TYPE: ${{ github.event.inputs.semver-type }}
        TARGET_BRANCH: ${{ steps.extract_branch.outputs.branch }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npx release-please@^14.1.1 release-pr \
          --token="$GH_TOKEN" \
          --repo-url=philipp-hinteregger/release-please-test \
          --target-branch=$TARGET_BRANCH
