name: Create Release PR
on:
  push:
    branches:
      - 'main'
      - '[0-9]+.[0-9]*.x'

defaults:
  run:
    shell: bash
jobs:
  prepare:
    name: Prepare release run
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Find next version number
      id: version_number
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npx release-please@^14.17.0 release-pr \
          --token="$GH_TOKEN" \
          --repo-url=philipp-hinteregger/release-please-test \
          --dry-run=true > release-please-output

        echo "::set-output name=RELEASE_VERSION::$(cat release-please-output | grep '): release' | cut -d ' ' -f4)"
        
    - name: Debug next version
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: cat release-please-output

    - name: Output new version
      env:
        VERSION_OUT: ${{ steps.version_number.outputs.RELEASE_VERSION }}
      run: |
        echo $VERSION_OUT

    - name: Find current branch
      id: extract_branch
      run: |
        branch=${GITHUB_REF#refs/heads/}
        echo "::set-output name=branch::${branch}"

    - name: Output target branch
      env:
        TARGET_BRANCH: ${{ steps.extract_branch.outputs.branch }}
      run: |
        echo $TARGET_BRANCH

    - name: Create release
      id: create_release
      env:
        SEMVER_TYPE: ${{ github.event.inputs.semver-type }}
        TARGET_BRANCH: ${{ steps.extract_branch.outputs.branch }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npx release-please@^14.1.1 release-pr \
          --token="$GH_TOKEN" \
          --repo-url=philipp-hinteregger/release-please-test \
          --target-branch=$TARGET_BRANCH
